// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxbxebhggvdipljlhpkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4YnhlYmhnZ3ZkaXBsamxocGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDY1MDUsImV4cCI6MjA2NDcyMjUwNX0.Cf7d4p5wm-kf1TEpU7hb7GNGUkZIk1kRAC0f3ZuTW4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);